import type { RefObject } from 'react'
import { PanelLeftClose, PanelLeftOpen, Pencil, Search, Settings, SquarePen, Trash2 } from 'lucide-react'
import type { PortableAIConversation } from '../portableAI'

type SidebarProps = { collapsed: boolean; conversations: PortableAIConversation[]; groupedConversations: Record<string, PortableAIConversation[]>; selectedId: string | null; searchValue: string; isSending: boolean; aiStatusLabel: string; hasStatusError: boolean; searchInputRef: RefObject<HTMLInputElement | null>; onToggle: () => void; onNewChat: () => void; onSearchChange: (value: string) => void; onSelect: (id: string) => void; onRename: (conversation: PortableAIConversation) => void; onDelete: (id: string) => void; onSettings: () => void }

export function Sidebar({ collapsed, conversations, groupedConversations, selectedId, searchValue, isSending, aiStatusLabel, hasStatusError, searchInputRef, onToggle, onNewChat, onSearchChange, onSelect, onRename, onDelete, onSettings }: SidebarProps) {
  return <aside className={`flex min-h-0 min-w-0 flex-col bg-[var(--sidebar-bg)] transition-[width,min-width] duration-200 ${collapsed ? 'w-16' : 'w-[260px] max-[900px]:w-[220px] max-[700px]:w-[180px]'}`}>
    <div className="flex min-h-[52px] items-center justify-between px-3 pb-2 pt-3"><div className="flex min-w-0 items-center gap-2">{!collapsed && <span className="whitespace-nowrap text-[0.95rem] font-semibold">PORTABLE.AI</span>}</div><button type="button" className="inline-flex size-8 items-center justify-center rounded-lg text-[var(--text-secondary)] hover:bg-[var(--surface-hover)]" onClick={onToggle} aria-label={collapsed ? 'Expand sidebar' : 'Collapse sidebar'}>{collapsed ? <PanelLeftOpen size={17} /> : <PanelLeftClose size={17} />}</button></div>
    <button className="mx-2 mb-1 flex h-10 items-center gap-2.5 rounded-lg px-2.5 text-sm font-medium text-[var(--text-primary)] hover:bg-[var(--surface-hover)] disabled:cursor-not-allowed disabled:opacity-65" type="button" onClick={onNewChat} disabled={isSending}><SquarePen size={17} />{!collapsed && 'New chat'}</button>
    {!collapsed && <div className="mx-2 mb-2 flex h-9 items-center gap-2.5 rounded-lg px-2.5 text-[var(--text-secondary)] hover:bg-[var(--surface-hover)]"><Search size={16} /><input ref={searchInputRef} type="text" value={searchValue} onChange={(event) => onSearchChange(event.target.value)} placeholder="Search" className="min-w-0 flex-1 bg-transparent text-sm text-[var(--text-primary)] outline-none placeholder:text-[var(--text-muted)]" /></div>}
    {!collapsed && <div className="min-h-0 flex-1 overflow-y-auto px-2 pb-2 [scrollbar-gutter:stable]">{conversations.length === 0 ? <div className="px-3 py-[22px] text-xs text-[var(--text-muted)]"><strong className="block text-[0.84rem] text-[var(--text-secondary)]">No conversations yet</strong><span>Start a new chat to get started.</span></div> : Object.entries(groupedConversations).map(([groupName, items]) => items.length > 0 && <div key={groupName} className="mb-3"><div className="px-2.5 pb-1 pt-2 text-xs text-[var(--text-muted)]">{groupName}</div><div className="flex flex-col gap-0.5">{items.map((conversation) => <div key={conversation.id} className={`group flex h-9 items-center gap-2 rounded-lg px-2.5 ${conversation.id === selectedId ? 'bg-[var(--surface-strong)]' : 'hover:bg-[var(--surface-hover)]'}`}><button type="button" className="min-w-0 flex-1 truncate bg-transparent p-0 text-left text-sm text-[var(--text-primary)] disabled:opacity-65" onClick={() => onSelect(conversation.id)} disabled={isSending}><span className="truncate">{conversation.title}</span></button><button type="button" className="inline-flex size-6 shrink-0 items-center justify-center rounded-md text-[var(--text-muted)] opacity-0 hover:bg-[var(--surface-hover)] hover:text-[var(--text-primary)] group-hover:opacity-100" onClick={() => onRename(conversation)} aria-label={`Rename ${conversation.title}`}><Pencil size={13} /></button><button type="button" className="inline-flex size-6 shrink-0 items-center justify-center rounded-md text-[var(--text-muted)] opacity-0 hover:bg-[var(--surface-hover)] hover:text-[var(--text-primary)] group-hover:opacity-100" onClick={() => onDelete(conversation.id)} aria-label={`Delete ${conversation.title}`}><Trash2 size={13} /></button></div>)}</div></div>)}</div>}
    <div className="flex flex-col gap-2.5 border-t border-[var(--border)] px-2 pb-3 pt-2.5"><button type="button" className="flex h-9 items-center gap-2.5 rounded-lg px-2.5 text-sm text-[var(--text-secondary)] hover:bg-[var(--surface-hover)]" onClick={onSettings}><Settings size={16} />{!collapsed && 'Settings'}</button>{!collapsed && <div className="flex items-center gap-2 px-2.5 text-xs text-[var(--text-muted)]"><span className={`size-1.5 rounded-full bg-[var(--success)] ${hasStatusError ? 'bg-orange-500' : ''}`} /><span>{aiStatusLabel}</span></div>}</div>
  </aside>
}
